language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
before_install:
  - travis_retry composer self-update
  - yes | pecl install swoole
  - composer install
script:
  - cp .env-default .env.testing
  - phpunit